version: 2
jobs:
  build:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/angular-aws
    branches:
      only:
        - v2
    steps:
      - checkout
      - type: shell
        command: |
          cd web
          ls
          ng -v
          npm install
          ng build
          aws s3 sync dist/ s3://unite-framework --delete
          npm run doc
          aws s3 sync dist/ s3://unite-framework-docs --delete
